
server:
  port: 8080

spring:
  application:
    name: rmi-client-a

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true # Optional, for preferring IP address in registration
